import type { Extra, Resort, SpaPackage, ResortTag } from "./data.types";

export const TAG_LABELS: Record<ResortTag, string> = {
  "thermal-pools": "Thermal pools",
  "adults-only": "Adults only",
  beachfront: "Beachfront",
  mountain: "Mountain",
  overwater: "Overwater villas",
  "hot-springs": "Hot springs",
  yoga: "Yoga & wellness",
  "family-friendly": "Family friendly",
};

export const RESORTS: Resort[] = [
  {
    id: "silfra-lagoon",
    name: "Silfra Lagoon Retreat",
    location: "Grindavík",
    country: "Iceland",
    region: "Nordics",
    rating: 4.9,
    reviewCount: 1284,
    pricePerNight: 420,
    gradient: ["#7fd4e8", "#2e7f96"],
    emoji: "🧊",
    tagline: "Steam rising off milky-blue geothermal water, under the northern lights.",
    description:
      "Carved into a lava field on the Reykjanes peninsula, Silfra Lagoon Retreat is built around a private geothermal lagoon kept at a constant 38°C. Every suite faces the water, and the in-lagoon swim-up bar serves Icelandic botanicals while you soak. Winter stays come with a wake-up call when the aurora appears.",
    amenities: ["Private geothermal lagoon", "Swim-up bar", "Sauna village", "Aurora wake-up service", "Fine-dining restaurant", "Free parking"],
    spaHighlights: ["Silica mud ritual", "In-water flotation massage", "Cold-plunge circuit", "Lava-stone therapy"],
    tags: ["thermal-pools", "hot-springs", "adults-only"],
    rooms: [
      { id: "lagoon-view", name: "Lagoon View Suite", description: "Floor-to-ceiling windows over the lagoon, heated floors, rain shower.", sleeps: 2, pricePerNight: 420 },
      { id: "lava-suite", name: "Lava Suite", description: "Private outdoor geothermal pool set into the lava field.", sleeps: 2, pricePerNight: 640 },
      { id: "aurora-villa", name: "Aurora Villa", description: "Detached villa with glass roof for northern-lights viewing from bed.", sleeps: 4, pricePerNight: 890 },
    ],
  },
  {
    id: "ubud-canopy",
    name: "Ubud Canopy Sanctuary",
    location: "Ubud, Bali",
    country: "Indonesia",
    region: "Southeast Asia",
    rating: 4.8,
    reviewCount: 2102,
    pricePerNight: 260,
    gradient: ["#8fd6a8", "#2e8f6e"],
    emoji: "🌿",
    tagline: "Treetop villas and open-air treatments above the Ayung river valley.",
    description:
      "Suspended in the jungle canopy outside Ubud, this sanctuary pairs Balinese healing traditions with river-valley views. Mornings start with sunrise yoga on the ridge deck; afternoons drift between the three-tier infinity pool and the open-air spa pavilions.",
    amenities: ["Three-tier infinity pool", "Ridge yoga deck", "Open-air spa pavilions", "Plant-based restaurant", "Rice-field walks", "Airport shuttle"],
    spaHighlights: ["Traditional Balinese massage", "Flower bath ceremony", "Jamu wellness elixirs", "Sound-healing sessions"],
    tags: ["yoga", "adults-only", "mountain"],
    rooms: [
      { id: "canopy-room", name: "Canopy Room", description: "Treehouse-style room with valley balcony and outdoor shower.", sleeps: 2, pricePerNight: 260 },
      { id: "river-villa", name: "River Pool Villa", description: "Private plunge pool overlooking the Ayung river.", sleeps: 2, pricePerNight: 410 },
      { id: "ridge-residence", name: "Ridge Residence", description: "Two-bedroom residence with full-length infinity pool.", sleeps: 4, pricePerNight: 720 },
    ],
  },
  {
    id: "alpenruhe",
    name: "Alpenruhe Grand Spa",
    location: "Zermatt",
    country: "Switzerland",
    region: "Alps",
    rating: 4.7,
    reviewCount: 1647,
    pricePerNight: 510,
    gradient: ["#cfe7f5", "#5b86a8"],
    emoji: "🏔️",
    tagline: "A century-old grand hotel with a glass-walled spa facing the Matterhorn.",
    description:
      "Alpenruhe has hosted alpine convalescents since 1908. Its modern wing holds a 2,800 m² spa where every pool, sauna and relaxation bed faces the Matterhorn. After a day in the panoramic thermal circuit, dinner is a seven-course affair in the wood-panelled Belle Époque dining room.",
    amenities: ["2,800 m² panoramic spa", "Indoor-outdoor thermal pool", "Six sauna types", "Michelin-starred dining", "Ski storage & concierge", "Kids' club (winter)"],
    spaHighlights: ["Alpine herb sauna rituals", "Edelweiss anti-aging facials", "Hay baths", "Altitude recovery massage"],
    tags: ["mountain", "thermal-pools", "family-friendly"],
    rooms: [
      { id: "alpine-classic", name: "Alpine Classic", description: "South-facing room with Matterhorn view and marble bath.", sleeps: 2, pricePerNight: 510 },
      { id: "panorama-junior", name: "Panorama Junior Suite", description: "Corner suite with window bathtub facing the peak.", sleeps: 3, pricePerNight: 750 },
      { id: "tower-suite", name: "Belle Époque Tower Suite", description: "The original 1908 tower, restored, with private spa room.", sleeps: 4, pricePerNight: 1280 },
    ],
  },
  {
    id: "terme-di-sole",
    name: "Terme di Sole",
    location: "Val d'Orcia, Tuscany",
    country: "Italy",
    region: "Mediterranean",
    rating: 4.6,
    reviewCount: 980,
    pricePerNight: 330,
    gradient: ["#f3d9a4", "#c98e4a"],
    emoji: "🍇",
    tagline: "Etruscan hot springs, cypress hills and very long lunches.",
    description:
      "A restored borgo above natural travertine terraces where thermal water has flowed since Etruscan times. Days here follow a gentle rhythm: a soak at dawn, a vineyard walk, a four-hour lunch, another soak. The wine-therapy spa uses Sangiovese grapes from the estate's own vines.",
    amenities: ["Natural travertine hot springs", "Wine-therapy spa", "Estate vineyard & cellar", "Cooking school", "Outdoor sunset pool", "E-bike rental"],
    spaHighlights: ["Sangiovese grape-seed scrub", "Thermal mud wraps", "Olive-oil massage", "Dawn spring bathing"],
    tags: ["hot-springs", "thermal-pools", "family-friendly"],
    rooms: [
      { id: "borgo-room", name: "Borgo Room", description: "Stone-walled room in the old village with valley views.", sleeps: 2, pricePerNight: 330 },
      { id: "cypress-suite", name: "Cypress Suite", description: "Suite with private terrace above the travertine terraces.", sleeps: 2, pricePerNight: 480 },
      { id: "farmhouse", name: "Vineyard Farmhouse", description: "Whole farmhouse with kitchen, garden and plunge pool.", sleeps: 6, pricePerNight: 940 },
    ],
  },
  {
    id: "noonu-atoll",
    name: "Noonu Atoll Haven",
    location: "Noonu Atoll",
    country: "Maldives",
    region: "Indian Ocean",
    rating: 4.9,
    reviewCount: 1531,
    pricePerNight: 780,
    gradient: ["#7ee0d2", "#1f8fa8"],
    emoji: "🐚",
    tagline: "Overwater villas with glass floors and an underwater treatment room.",
    description:
      "Reached by seaplane, this single-island resort circles a turquoise lagoon. Each overwater villa has steps straight into the water, and the spa's signature suite sits four metres below the surface, so reef fish drift past while you're massaged. Evenings end with barefoot sandbank dinners.",
    amenities: ["Underwater spa suite", "House reef snorkelling", "Overwater yoga shala", "Sandbank private dining", "Dive centre", "Seaplane transfers"],
    spaHighlights: ["Underwater signature massage", "Coconut-and-lime body polish", "Couples' sunset ritual", "Ocean-sound meditation"],
    tags: ["overwater", "beachfront", "adults-only", "yoga"],
    rooms: [
      { id: "water-villa", name: "Overwater Villa", description: "Glass-floor lounge, private deck with lagoon ladder.", sleeps: 2, pricePerNight: 780 },
      { id: "sunset-pool-villa", name: "Sunset Pool Villa", description: "West-facing overwater villa with infinity plunge pool.", sleeps: 3, pricePerNight: 1150 },
      { id: "beach-residence", name: "Beach Residence", description: "Two-bedroom beachfront residence with private pool and butler.", sleeps: 5, pricePerNight: 1690 },
    ],
  },
  {
    id: "yamanaka-onsen",
    name: "Yamanaka Onsen Ryokan",
    location: "Kaga, Ishikawa",
    country: "Japan",
    region: "East Asia",
    rating: 4.8,
    reviewCount: 743,
    pricePerNight: 390,
    gradient: ["#f6c6c0", "#a85b6b"],
    emoji: "🏮",
    tagline: "A 300-year-old ryokan on a gorge of maples and healing waters.",
    description:
      "Seventeen tatami rooms above the Kakusenkei gorge, where onsen water has been prized since the 8th century. Stays include kaiseki dinners served in-room, morning forest bathing along the river path, and private open-air cypress baths bookable by the hour.",
    amenities: ["Indoor & open-air onsen", "Private kaiseki dining", "Cypress private baths", "Tea ceremony room", "Yukata & geta provided", "Gorge-side garden"],
    spaHighlights: ["Private rotenburo bathing", "Shiatsu massage", "Forest bathing walks", "Green-tea body wrap"],
    tags: ["hot-springs", "adults-only", "mountain"],
    rooms: [
      { id: "tatami-river", name: "River Tatami Room", description: "Classic tatami room with gorge view and futon bedding.", sleeps: 2, pricePerNight: 390 },
      { id: "tatami-bath", name: "Tatami Room with Open-Air Bath", description: "Private cypress rotenburo on a maple-shaded balcony.", sleeps: 2, pricePerNight: 560 },
      { id: "annex-suite", name: "Annex Garden Suite", description: "Detached suite with garden, bath and dedicated attendant.", sleeps: 4, pricePerNight: 820 },
    ],
  },
  {
    id: "rio-celeste",
    name: "Río Celeste Hot Springs Lodge",
    location: "Tenorio, Guanacaste",
    country: "Costa Rica",
    region: "Central America",
    rating: 4.6,
    reviewCount: 612,
    pricePerNight: 290,
    gradient: ["#9be3c8", "#2e8f96"],
    emoji: "🦋",
    tagline: "Volcano-heated pools at the edge of a cloud-forest reserve.",
    description:
      "Eleven thatched bungalows beside a chain of volcano-fed pools, each a different temperature, descending through the rainforest. Sloths and toucans are daily visitors. The spa works with cacao, coffee and volcanic clay harvested within sight of your treatment table.",
    amenities: ["Seven cascading thermal pools", "Cloud-forest trails", "Wildlife guides", "Open-air rainforest spa", "Farm-to-table restaurant", "Volcano viewpoints"],
    spaHighlights: ["Volcanic clay wrap", "Cacao ceremony massage", "Coffee-scrub ritual", "Waterfall hydrotherapy"],
    tags: ["hot-springs", "family-friendly", "yoga", "mountain"],
    rooms: [
      { id: "forest-bungalow", name: "Forest Bungalow", description: "Thatched bungalow with hammock deck in the canopy.", sleeps: 2, pricePerNight: 290 },
      { id: "springs-bungalow", name: "Springs Bungalow", description: "Steps from the warmest pool, with outdoor stone bath.", sleeps: 3, pricePerNight: 380 },
      { id: "family-casita", name: "Family Casita", description: "Two-bedroom casita with private thermal plunge pool.", sleeps: 5, pricePerNight: 540 },
    ],
  },
  {
    id: "thira-cliffs",
    name: "Thira Cliffs Wellness House",
    location: "Santorini",
    country: "Greece",
    region: "Mediterranean",
    rating: 4.7,
    reviewCount: 1190,
    pricePerNight: 460,
    gradient: ["#dceefb", "#3a6ea5"],
    emoji: "🌊",
    tagline: "Cave suites carved into the caldera, sea-salt therapies, endless blue.",
    description:
      "Whitewashed cave suites stacked into the caldera cliff, each with a private heated plunge pool facing the volcano. The spa specialises in thalassotherapy — sea-salt scrubs, seaweed wraps and a saltwater flotation grotto carved into the rock.",
    amenities: ["Saltwater flotation grotto", "Cliff-edge infinity pool", "Sunset yoga terrace", "Wine bar with caldera view", "Concierge & transfers", "Catamaran day trips"],
    spaHighlights: ["Thalassotherapy circuit", "Sea-salt body scrub", "Volcanic stone massage", "Flotation grotto sessions"],
    tags: ["beachfront", "adults-only", "yoga", "thermal-pools"],
    rooms: [
      { id: "cave-suite", name: "Cave Suite", description: "Carved cave suite with caldera-view terrace and plunge pool.", sleeps: 2, pricePerNight: 460 },
      { id: "sunset-suite", name: "Sunset Grand Suite", description: "Top-row suite with heated pool and outdoor dining pergola.", sleeps: 2, pricePerNight: 690 },
      { id: "captains-house", name: "Captain's House", description: "Restored 1860s sea-captain's house with two bedrooms and pool.", sleeps: 4, pricePerNight: 1040 },
    ],
  },
];

export const SPA_PACKAGES: SpaPackage[] = [
  {
    id: "signature-serenity",
    name: "Signature Serenity",
    description: "The resort's flagship ritual — one full treatment day for a deep reset.",
    pricePerPerson: 180,
    treatments: ["90-min signature massage", "Body scrub or wrap", "Thermal circuit access", "Herbal tea ceremony"],
  },
  {
    id: "couples-escape",
    name: "Couples' Escape",
    description: "Side-by-side treatments and a private bathing session for two.",
    pricePerPerson: 240,
    treatments: ["Couples' massage", "Private bath or pool hour", "Sparkling wine & fruit", "Late checkout"],
  },
  {
    id: "deep-recovery",
    name: "Deep Recovery",
    description: "For tired bodies — three treatment days focused on muscles and sleep.",
    pricePerPerson: 420,
    treatments: ["3 × deep-tissue massages", "Cold plunge & sauna coaching", "Sleep-ritual turndown", "Recovery nutrition menu"],
  },
  {
    id: "glow-ritual",
    name: "Glow Ritual",
    description: "Skin-first program with facials and mineral bathing.",
    pricePerPerson: 310,
    treatments: ["2 × signature facials", "Mineral or mud bath", "Scalp & hair treatment", "Daily thermal access"],
  },
];

export const EXTRAS: Extra[] = [
  { id: "flights", name: "Return flights", description: "Economy return flights from your nearest hub.", price: 480, per: "person" },
  { id: "transfer", name: "Airport transfers", description: "Private round-trip transfer between airport and resort.", price: 120, per: "booking" },
  { id: "breakfast", name: "Daily breakfast", description: "Full breakfast for the whole stay.", price: 28, per: "person" },
  { id: "sunrise-yoga", name: "Sunrise yoga pass", description: "Daily guided morning sessions for the whole stay.", price: 60, per: "person" },
  { id: "insurance", name: "Trip protection", description: "Full cancellation and medical coverage.", price: 45, per: "person" },
];

export function getResort(id: string): Resort | undefined {
  return RESORTS.find((r) => r.id === id);
}
